spring.application.name=prototipo-reservas

# Configuración de Supabase - Transaction Pooler
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&preparedStatementCacheQueries=0
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.xlvtoslopxmjuqmznxjd
spring.datasource.password=IOC2026RoomyApp

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Configuración JWT
jwt.secret=${JWT_SECRET:mi_clave_super_secreta_que_debe_tener_minimo_256_bits_para_HS256}
jwt.expiration=604800000

